//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ISTool.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_POPUP                       102
#define IDR_MAINFRAME                   128
#define IDD_SETUP_COMPILER              130
#define IDD_FILES                       132
#define IDD_SETUP_APPLICATION           134
#define IDD_SETUP_PAGES                 135
#define IDD_DIRS                        136
#define IDD_ICONS                       137
#define IDD_INI                         138
#define IDD_DELETE                      139
#define IDS_LANGUAGE                    140
#define IDD_RUN                         141
#define IDS_AUTHOR                      141
#define IDD_REGISTRY                    142
#define IDS_VERSION                     142
#define IDS_DOWNLOADING_UPDATE          143
#define IDD_SETUP_APPEARANCE            148
#define IDD_ADD_DIRECTORY               151
#define IDS_MERGEFILE                   152
#define IDS_STRING156                   156
#define IDB_IMAGELIST                   161
#define IDD_FILE_ASSOCIATION            166
#define IDD_MESSAGE                     167
#define IDD_PREFS_GENERAL               168
#define IDD_SELECTFONTS                 176
#define IDD_CUSTOMIZE                   177
#define IDD_SETUP_UNINSTALL             178
#define IDR_COMBOPOPUP                  180
#define IDD_ODBC                        181
#define IDD_PREFS_PATHS                 185
#define IDD_SYSPATH                     187
#define IDD_TYPE                        191
#define IDD_COMPONENT                   192
#define IDD_COMMON_NEW                  193
#define IDD_COMPILE_STEP_EDIT           199
#define IDD_COMMON_TASKS                200
#define IDD_TASK                        201
#define IDD_COMMON_COMPONENTS           202
#define IDD_VERSION                     217
#define IDD_COMPILE                     218
#define IDD_BDE_ALIAS                   219
#define IDD_IESHORTCUT                  220
#define IDD_UPDATES                     221
#define IDD_LANGOPTIONS                 222
#define IDB_GLYPHS                      223
#define IDI_ICON1                       228
#define IDB_XPTOOLBAR_SMALL1            231
#define IDB_XPTOOLBAR_SMALL2            232
#define IDR_TOOLBAR1                    234
#define ID_FILE_PRINT236                236
#define ID_FILE_PRINTPREVIEW            237
#define IDR_PRINTPREVIEW                240
#define IDB_IMAGELIST32                 244
#define ID_VIEW_SECTIONPANEL            245
#define IDB_IMAGELIST16                 248
#define IDI_ICON2                       251
#define IDI_ICON3                       252
#define IDD_DOWNLOAD                    253
#define ID_EDIT_GOTO                    254
#define IDD_GOTO                        255
#define ID_PROJECT_LOGFILE              257
#define IDC_LINENUMBER                  258
#define IDD_LOGFILE                     258
#define IDD_LANGUAGES                   259
#define IDD_SETUP_APPDIR                260
#define IDD_SETUP_USERINFO              262
#define IDD_SETUP_PROGRAMGROUP          263
#define IDD_SETUP_DISKSPANNING          264
#define IDD_COMMON_LANGUAGES            265
#define IDD_PREFS_EDITOR                268
#define IDD_SELECT_LANGUAGEFILES        269
#define IDD_CUSTOMMESSAGE               270
#define IDC_COMPRESSLEVEL               1003
#define IDC_SPINCOMPRESSLEVEL           1004
#define IDC_DISKCLUSTERSIZE             1005
#define IDC_DISKSPANNING                1007
#define IDC_OUTPUTDIR                   1008
#define IDC_RESERVEBYTES                1009
#define IDC_SOURCEDIR                   1010
#define IDC_CHECKUSESETUPLDR            1011
#define IDC_SOURCE                      1014
#define IDC_DESTDIR                     1015
#define IDC_DESTNAME                    1016
#define IDC_READONLY                    1018
#define IDC_HIDDEN                      1019
#define IDC_SYSTEM                      1020
#define IDC_FONTINSTALL                 1021
#define IDC_COMPARETIMESTAMP            1022
#define IDC_DEFAULTGROUPNAME            1023
#define IDC_DELETEAFTERINSTALL          1024
#define IDC_FONTISNTTRUETYPE            1025
#define IDC_ISREADME                    1026
#define IDC_REGSERVER                   1027
#define IDC_RESTARTREPLACE              1028
#define IDC_SHAREDFILE                  1029
#define IDC_DISABLEDIRPAGE              1030
#define IDC_DEFAULTDIRNAME              1032
#define IDC_CREATEAPPDIR                1033
#define IDC_ALLOWNOICONS                1036
#define IDC_UNINSTALLABLE               1037
#define IDC_APPNAME                     1040
#define IDC_APPVERNAME                  1041
#define IDC_APPCOPYRIGHT                1042
#define IDC_DISABLESTARTUPPROMPT        1043
#define IDC_BACKSOLID                   1045
#define IDC_BACKCOLOR                   1046
#define IDC_NAME                        1047
#define IDC_WIZARDIMAGEBACKCOLOR        1048
#define IDC_UNINSALWAYSUNINSTALL        1049
#define IDC_FILENAME                    1050
#define IDC_PARAMETERS                  1051
#define IDC_ICONFILENAME                1052
#define IDC_ICONINDEX                   1053
#define IDC_CREATEONLYIFFILEEXISTS      1054
#define IDC_RUNMINIMIZED                1055
#define IDC_UNINSNEVERUNINSTALL         1056
#define IDC_INFOBEFOREFILE              1057
#define IDC_DISABLEPROGRAMGROUPPAGE     1058
#define IDC_WORKINGDIR                  1059
#define IDC_SECTION                     1061
#define IDC_KEY                         1062
#define IDC_STRING                      1063
#define IDC_CREATEKEYIFDOESNTEXIST      1064
#define IDC_UNINSDELETEENTRY            1065
#define IDC_UNINSDELETESECTION          1066
#define IDC_UNINSDELETESECTIONIFEMPTY   1067
#define IDC_NOWAIT                      1068
#define IDC_CONFIRMOVERWRITE            1069
#define IDC_INFOAFTERFILE               1070
#define IDC_ROOT                        1071
#define IDC_SUBKEY                      1072
#define IDC_VALUETYPE                   1073
#define IDC_VALUENAME                   1074
#define IDC_VALUEDATA                   1075
#define IDC_CREATEVALUEIFDOESNTEXIST    1076
#define IDC_UNINSCLEARVALUE             1077
#define IDC_HOMEPAGE                    1078
#define IDC_UNINSDELETEKEYIFEMPTY       1079
#define IDC_REGTYPELIB                  1081
#define IDC_EXTERNAL                    1082
#define IDC_SKIPIFSOURCEDOESNTEXIST     1083
#define IDC_SHELLEXEC                   1084
#define IDC_USEAPPPATHS                 1085
#define IDC_COMMENT                     1086
#define IDC_ALWAYSUSEPERSONALGROUP      1087
#define IDC_TYPE                        1088
#define IDC_EXTRADISKSPACEREQUIRED      1089
#define IDC_WINDOWVISIBLE               1090
#define IDC_WINDOWSHOWCAPTION           1091
#define IDC_WINDOWSTARTMAXIMIZED        1092
#define IDC_WINDOWRESIZABLE             1093
#define IDC_OUTPUTBASEFILENAME          1094
#define IDC_ENABLEDIRDOESNTEXISTWARNING 1095
#define IDC_MERGEDUPLICATEFILES         1097
#define IDC_ADMINPRIVILEGESREQUIRED     1098
#define IDC_CHANGESASSOCIATIONS         1099
#define IDC_VERSION                     1100
#define IDC_WIZARDIMAGEFILE             1101
#define IDC_PASSWORD                    1103
#define IDC_UNINSDELETEKEY              1105
#define IDC_UNINSDELETEVALUE            1106
#define IDC_EMAIL                       1107
#define IDC_MINIMUM_VERSION_9X          1123
#define IDC_MINIMUM_VERSION_NT          1124
#define IDC_ONLY_BELOW_VERSION_9X       1125
#define IDC_ONLY_BELOW_VERSION_NT       1126
#define IDC_CHECK_ADD_DIRECTORIES       1127
#define IDC_CHECK_INCLUDE_SUB_DIRECTORIES 1128
#define IDC_CHECK_ADD_FILES             1129
#define IDC_BTN_INFOAFTERFILE           1130
#define IDC_BTN_INFOBEFOREFILE          1131
#define IDC_BTN_LICENSEFILE             1132
#define IDC_BTN_SOURCE                  1133
#define IDC_BTN_SOURCE_DIR              1134
#define IDC_BTN_WIZARD_IMAGE_FILE       1135
#define IDC_OUTPUTMANIFESTFILE_BUTTON   1135
#define IDC_BTN_OUTPUT_DIR              1137
#define IDC_DIRS_DELETEAFTERINSTALL     1138
#define IDC_DIRS_UNINSNEVERUNINSTALL    1139
#define IDC_WAITUNTILIDLE               1142
#define IDC_FA_FILE_EXTENSION           1146
#define IDC_FA_TYPE_NAME                1147
#define IDC_FA_DOCUMENT_DESCRIPTION     1148
#define IDC_FA_ASSOCIATE_WITH           1149
#define IDC_ALLOWROOTDIRECTORY          1150
#define IDC_OVERWRITEREADONLY           1151
#define IDC_PRESERVESTRINGTYPE          1152
#define IDC_MESSAGE_KEY                 1153
#define IDC_MESSAGE_TEXT                1154
#define IDC_LICENSEFILE                 1155
#define IDC_MESSAGE_DEFAULT             1156
#define IDC_ICONS_NAME                  1157
#define IDC_ICONS_UNINSNEVERUNINSTALL   1158
#define IDC_INI_FILENAME                1159
#define IDC_DELETE_NAME                 1160
#define IDC_RUN_FILENAME                1161
#define IDC_RUN_PARAMETERS              1162
#define IDC_RUN_WORKINGDIR              1163
#define IDC_APP_MINIMUM_VERSION_9X      1164
#define IDC_APP_MINIMUM_VERSION_NT      1165
#define IDC_APP_ONLY_BELOW_VERSION_9X   1166
#define IDC_APP_ONLY_BELOW_VERSION_NT   1167
#define IDC_PREFS1_COMPILERDIR          1168
#define IDC_PREFS1_COMPILERDIR_B        1170
#define IDC_DISABLEFINISHEDPAGE         1171
#define IDC_PREFS1_LANGUAGEDLL          1172
#define IDC_FONTLIST                    1175
#define IDC_PREFS1_LANGUAGEDLL_BTN      1177
#define IDC_COLUMNLIST                  1178
#define IDC_APPID                       1179
#define IDC_UNINSTALLLOGMODE            1180
#define IDC_CREATEUNINSTALLREGKEY       1182
#define IDC_APPPUBLISHER                1184
#define IDC_APPPUBLISHERURL             1186
#define IDC_APPSUPPORTURL               1188
#define IDC_APPUPDATESURL               1190
#define IDC_APPVERSION                  1191
#define IDC_USEPREVIOUSAPPDIR           1192
#define IDC_ISVERSION                   1193
#define IDC_ISHOMEPAGE                  1194
#define IDC_LIST                        1195
#define IDC_BACKCOLORDIRECTION          1206
#define IDC_UNINSTALLFILESDIR           1207
#define IDC_BACKCOLOR2                  1208
#define IDC_DAO                         1210
#define IDC_MSJET                       1211
#define IDC_ODBCDIRECT                  1212
#define IDC_MSJETREPLICATION            1213
#define IDC_XBASEFORMATS                1214
#define IDC_PARADOXFORMATS              1215
#define IDC_TEXTFILES                   1216
#define IDC_SPREADSHEETFILES            1217
#define IDC_LOTUSFORMATS                1218
#define IDC_EXCHANGEFORMATS             1219
#define IDC_ASSOCIATE_ISTOOL            1258
#define IDC_PROJECT_TYPE                1260
#define IDC_FILE_LIST                   1261
#define IDC_SYSFILE                     1262
#define IDC_SYSPATH                     1263
#define IDC_SYSPATH_B                   1264
#define IDC_SYSDESTDIR                  1265
#define IDC_USEPREVIOUSGROUP            1267
#define IDC_DIREXISTSWARNING            1268
#define IDC_UNINSTALLDISPLAYICON        1269
#define IDC_RESTARTCOMPUTER             1270
#define IDC_UNINSTALLDISPLAYICONINDEX   1271
#define IDC_UNINSTALLDISPLAYNAME        1272
#define IDC_TYPE_NAME                   1273
#define IDC_TYPE_DESCRIPTION            1274
#define IDC_TYPE_ISCUSTOM               1275
#define IDC_COMPONENT_NAME              1276
#define IDC_COMPONENT_DESCRIPTION       1277
#define IDC_COMPONENT_FIXED             1278
#define IDC_COMMON_COMPONENTLIST        1279
#define IDC_COMPONENT_TYPES             1280
#define IDC_COMMON_COMPONENTSTEXT       1282
#define IDC_GENERAL_IGNOREDEFAULTS      1283
#define IDC_RUN_RUNMINIMIZED            1284
#define IDC_RUN_SKIPIFDOESNTEXIST       1285
#define IDC_REGISTRY_DELETEKEY          1286
#define IDC_REGISTRY_DELETEVALUE        1287
#define IDC_RUN_RUNONCEID               1288
#define IDC_COMPONENT_RESTART           1290
#define IDC_EXT_USEPREVIOUSSETUPTYPE    1292
#define IDC_EXT_DISABLEREADYMEMO        1293
#define IDC_EXT_WIZARDSMALLIMAGEFILE    1295
#define IDC_EXT_WIZARDSMALLIMAGEFILE2   1296
#define IDC_RUN_POSTINSTALL             1297
#define IDC_RUN_UNCHECKED               1298
#define IDC_RUN_DESCRIPTION             1299
#define IDC_EXT_ALWAYSSHOWCOMPONENTSLIST 1300
#define IDC_COMPONENT_DISABLENOUNINSTALLWARNING 1301
#define IDC_RUN_SKIPIFSILENT            1302
#define IDC_RUN_SKIPIFNOTSILENT         1303
#define IDC_REGISTRY_NOERROR            1305
#define IDC_EXT_FLATCOMPONENTSLIST      1306
#define IDC_EXT_SHOWCOMPONENTSIZES      1307
#define IDC_CSE_NAME                    1309
#define IDC_CSE_PARAMETERS              1310
#define IDC_CSE_RUN_MINIMIZED           1311
#define IDC_CSE_ABORT_ON_ERROR          1312
#define IDC_APPMUTEX                    1315
#define IDC_ICONS_CLOSEONEXIT           1316
#define IDC_ICONS_DONTCLOSEONEXIT       1317
#define IDC_REGISTRY_DONT_CREATE_KEY    1319
#define IDC_GENERAL_OPENLAST            1323
#define IDC_TASKS_LIST                  1324
#define IDC_TASKS_NOTE                  1325
#define IDC_TASK_NAME                   1326
#define IDC_TASK_DESCRIPTION            1327
#define IDC_TASK_GROUP_DESCRIPTION      1328
#define IDC_TASK_EXCLUSIVE              1329
#define IDC_TASK_UNCHECKED              1330
#define IDC_EXT_USE_PREVIOUS_TASKS      1331
#define IDC_ADD_DIRECTORY_WILDCARD      1332
#define IDC_UPDATEUNINSTALLLOGAPPNAME   1333
#define IDC_GENERAL_USENEWSCRIPTWIZARD  1355
#define IDC_VER_MAJOR                   1356
#define IDC_VER_MINOR                   1357
#define IDC_VER_BUILD                   1358
#define IDC_VER_SP                      1359
#define IDC_BTN_MINVERSIONWIN           1360
#define IDC_BTN_MINVERSIONNT            1361
#define IDC_BTN_BELOWVERSIONWIN         1362
#define IDC_BTN_BELOWVERSIONNT          1363
#define IDC_COMPILE_LIST                1364
#define IDC_COMPONENTS_BUTTON           1364
#define IDC_VER_COMBO                   1365
#define IDC_LANGUAGES_BUTTON            1365
#define IDC_TASKS_BUTTON                1366
#define IDC_GENERAL_REPLACECOPY         1367
#define IDC_GENERAL_AUTOCOMPONENTSELECT 1369
#define IDC_GENERAL_TEST_COMPILED_SETUP 1370
#define IDC_BTN_CSE_NAME                1371
#define IDC_RUN_RUNMAXIMIZED            1372
#define IDC_ICONS_RUNMAXIMIZED          1373
#define IDC_COMPONENT_EXTRADISKSPACEREQUIRED 1375
#define IDC_FILES_ONLYIFDESTFILEEXISTS  1376
#define IDC_SCRIPTING_CHECK             1378
#define IDC_BDE_OVERWRITE               1379
#define IDC_BDE_ALIAS_NAME              1380
#define IDC_BDE_DATA_DIRECTORY          1381
#define IDC_BDE_DRIVER_NAME             1382
#define IDC_ISVERSION_INSTALLED         1384
#define IDC_EXT_DISABLE_READY_PAGE      1385
#define IDC_IESHORTCUT_FILENAME         1386
#define IDC_IESHORTCUT_URL              1387
#define IDC_RUN_STATUSMSG               1388
#define IDC_RECURSESUBDIRS              1389
#define IDC_TASK_RESTART                1390
#define IDC_FILES_NOREGERROR            1391
#define IDC_TASK_CHECKED_ONCE           1392
#define IDC_FA_ICON_FILENAME            1393
#define IDC_FA_ICON_INDEX               1394
#define IDC_ICONS_HOTKEY                1395
#define IDC_ALWAYSSHOWDIRONREADYPAGE    1396
#define IDC_ALWAYSSHOWGROUPONREADYPAGE  1397
#define IDC_UPDATES_WEB_PAGE            1398
#define IDC_UPDATES_INFO                1399
#define IDC_LANGOPTIONS_LANGUAGENAME    1400
#define IDC_LANGOPTIONS_LANGUAGEID      1401
#define IDC_LANGOPTIONS_DIALOGFONTNAME  1402
#define IDC_LANGOPTIONS_TITLEFONTNAME   1403
#define IDC_LANGOPTIONS_WELCOMEFONTNAME 1404
#define IDC_LANGOPTIONS_COPYRIGHTFONTNAME 1405
#define IDC_LANGOPTIONS_DIALOGFONTSIZE  1406
#define IDC_SPIN1                       1407
#define IDC_LANGOPTIONS_TITLEFONTSIZE   1408
#define IDC_SPIN2                       1410
#define IDC_LANGOPTIONS_WELCOMEFONTSIZE 1412
#define IDC_RUN_HIDEWIZARD              1413
#define IDC_SPIN3                       1414
#define IDC_LANGOPTIONS_COPYRIGHTFONTSIZE 1415
#define IDC_SPIN4                       1416
#define IDC_LANGOPTIONS_DIALOGFONTSTANDARDHEIGHT 1417
#define IDC_SPIN5                       1418
#define IDC_GENERAL_OVERWRITE_MESSAGES  1419
#define IDC_COMPRESSION                 1423
#define IDC_INTERNALCOMPRESSLEVEL       1424
#define IDC_SPININTERNALCOMPRESSLEVEL   1425
#define IDC_ALLOWUNCPATH                1426
#define IDC_USERINFOPAGE                1427
#define IDC_DEFAULTUSERINFONAME         1429
#define IDC_DEFAULTUSERINFOORG          1430
#define IDC_USEPREVIOUSUSERINFO         1431
#define IDC_TRANSLATOR                  1438
#define IDC_SETUPICONFILE_B             1439
#define IDC_CHECK_UNINSTALLRESTARTCOMPUTER 1540
#define IDC_UNINSRESTARTDELETE          1541
#define IDC_ALWAYSRESTART               1542
#define IDC_COMPONENTSEXCLUSIVE         1543
#define IDC_SHOWTASKSTREELINES          1544
#define IDC_RESTARTIFNEEDEDBYRUN        1545
#define IDC_DOWNLOAD                    1546
#define IDC_PRIVILEGESREQUIRED          1547
#define IDC_STARTUPSECTION              1548
#define IDC_DEFAULT                     1549
#define IDC_TRANSLATION                 1550
#define IDC_DOWNLOAD_DESTDIR            1551
#define IDC_PROMPTIFOLDER               1552
#define IDC_ONLYIFDOESNTEXIST           1553
#define IDC_IGNOREVERSION               1554
#define IDC_DONTCOPY                    1555
#define IDC_DOWNLOAD_SOURCE             1556
#define IDC_DOWNLOAD_DESTNAME           1557
#define IDC_DEFAULTUSERINFOSERIAL       1558
#define IDC_GUIDGEN                     1560
#define IDC_LOGFILE                     1561
#define IDC_LOGFILEBROWSE               1562
#define IDC_LOGFILEAPPEND               1563
#define IDC_TRANSVER                    1564
#define IDC_SHOWLANGUAGEDIALOG          1565
#define IDC_DISKSLICESIZE               1566
#define IDC_SLICESPERDISK               1567
#define IDC_LANGUAGES_MESSAGESFILE      1568
#define IDC_LANGUAGES_NAME              1569
#define IDC_LANGUAGES_MESSAGESFILE2     1570
#define IDC_LANGUAGES_LICENSEFILE2      1571
#define IDC_STATIC1                     1572
#define IDC_LANGUAGES_INFOBEFOREFILE2   1573
#define IDC_STATIC2                     1574
#define IDC_LANGUAGES_INFOAFTERFILE2    1575
#define IDC_STATIC3                     1576
#define IDC_STATIC4                     1577
#define IDC_STATIC5                     1578
#define IDC_STATIC6                     1579
#define IDC_STATIC7                     1580
#define IDC_STATIC8                     1581
#define IDC_STATIC9                     1582
#define IDC_STATICa                     1583
#define IDC_STATICb                     1584
#define IDC_ABORT                       1585
#define IDC_GOTOERROR                   1586
#define IDC_LANGUAGES_LICENSEFILE       1587
#define IDC_LANGUAGES_INFOBEFOREFILE    1588
#define IDC_SOLIDCOMPRESSION            1589
#define IDC_LANGUAGES_INFOAFTERFILE     1590
#define IDC_LANGUAGES_NOTE              1591
#define IDC_LANGUAGES_LIST              1592
#define IDC_FONTSIZE                    1594
#define IDC_FONTSIZESPIN                1595
#define IDC_UNINSREMOVEREADONLY         1596
#define IDC_RUNHIDDEN                   1600
#define IDC_ALLOWCANCELDURINGINSTALL    1601
#define IDC_PROGRESS                    1602
#define IDC_TIMESTAMPSINUTC             1604
#define IDC_LANGUAGEDETECTIONMETHOD     1605
#define IDC_COMPRESSLEVELCOMBO          1606
#define IDC_PERMISSIONS                 1607
#define IDC_BEFOREINSTALL               1608
#define IDC_AFTERINSTALL                1609
#define IDC_BEFOREINSTALL_T             1610
#define IDC_AFTERINSTALL_T              1611
#define IDC_MINVERSION                  1612
#define IDC_ONLYBELOWVERSION            1613
#define IDC_SCRIPTING                   1614
#define IDC_SETUPICONFILE               1615
#define IDC_TIMESTAMPROUNDING           1617
#define IDC_VERSIONINFOVERSION          1618
#define IDC_VERSIONINFOCOMPANY          1619
#define IDC_VERSIONINFODESCRIPTION      1620
#define IDC_VERSIONINFOTEXTVERSION      1621
#define IDC_FLAGS                       1622
#define IDC_ATTRIBUTES                  1623
#define IDC_TABSTOPVALUE                1624
#define IDC_PREPROCESS                  1625
#define IDC_WIZARDIMAGESTRETCH          1626
#define IDC_SHOWVERTICALTABLINES        1628
#define IDC_AUTOINDENT                  1629
#define IDC_STYLES                      1630
#define IDC_BOLD                        1631
#define IDC_ITALIC                      1632
#define IDC_UNDERLINE                   1633
#define IDC_STYLE                       1634
#define IDC_BACK                        1635
#define IDC_SHOWLINENUMBERS             1636
#define IDC_EXCLUDES                    1637
#define IDC_TOUCHDATE                   1640
#define IDC_TOUCHTIME                   1641
#define IDC_TOUCH                       1642
#define IDC_REPLACESAMEVERSION          1643
#define IDC_BROWSE                      1644
#define IDC_EDIT1                       1644
#define IDC_APPMODIFYPATH               1644
#define IDC_COMPONENTS                  1644
#define IDC_OUTPUTMANIFESTFILE          1644
#define IDC_EDIT                        1644
#define IDC_RUN_VERB                    1644
#define IDC_EXTERNALSIZE                1644
#define IDC_FORE                        1645
#define IDC_ENCRYPTION                  1645
#define IDC_LANGUAGES                   1645
#define IDC_SCHEME                      1646
#define IDC_NOENCRYPTION                1646
#define IDC_TASKS                       1646
#define IDC_SORTFILESBYEXTENSION        1647
#define IDC_DONTINHERITCHECK            1647
#define IDC_APPENDDEFAULTDIRNAME        1648
#define IDC_APPCOMMENTS                 1648
#define IDC_APPENDDEFAULTGROUPNAME      1649
#define IDC_APPCONTACT                  1649
#define IDC_NOOUTPUTEXEFILENAME         1650
#define IDC_EDIT4                       1650
#define IDC_APPREADMEFILE               1650
#define IDC_COMPRESSIONTHREADS          1650
#define IDC_NOCOMPRESSION               1651
#define IDC_CHECK2                      1652
#define IDC_DONTVERIFYCHECKSUM          1652
#define IDC_TERMINALSERVICESAWARE       1652
#define IDC_RUNASCURRENTUSER            1652
#define IDC_COMPONENTS_T                1653
#define IDC_TASKS_T                     1654
#define IDC_LANGUAGES_T                 1655
#define IDC_ADVANCED                    1656
#define IDC_UNINSNOSHAREDFILEPROMPT     1657
#define IDC_FOLDERSHORTCUT              1658
#define IDC_CHANGESENVIRONMENT          1659
#define IDC_CREATEALLSUBDIRS            1660
#define IDC_CHECKABLEALONE              1661
#define IDC_CHECK1                      1662
#define IDC_32BIT                       1662
#define IDC_SHOWUNDISPLAYABLELANGUAGES  1662
#define IDC_SETUPLOGGING                1662
#define IDC_SIGNEDUNINSTALLER           1662
#define IDC_ARCHITECTURESINSTALLIN64BITMODE 1663
#define IDC_EDIT3                       1664
#define IDC_ARCHITECTURESALLOWED        1664
#define IDC_SIGNEDUNINSTALLERDIR        1664
#define IDC_64BIT                       1665
#define IDC_EDIT2                       1666
#define IDC_VERSIONINFOCOPYRIGHT        1666
#define IDC_APPSUPPORTPHONE             1666
#define IDC_RUN_32BIT                   1667
#define IDC_RUN_64BIT                   1668
#define IDC_FILES_SOLIDBREAK            1669
#define IDC_STATIC_VERB                 1670
#define IDC_RUNASORIGINALUSER           1671
#define IDC_STATIC_EXTERNALSIZE         1672
#define IDC_SETNTFSCOMPRESSION          1673
#define IDC_CHECK4                      1674
#define IDC_UNSETNTFSCOMPRESSION        1674
#define IDC_BUTTON1                     1675
#define IDC_SIGNEDUNINSTALLERDIR2       1676
#define WTL_IDS_SAVEFILE                8608
#define WTL_IDS_SAVEFILECOPY            8609
#define WTL_IDS_OPENFILE                8611
#define ID_EDIT_NEWITEM                 32775
#define ID_POPUP_CREATEICON             32782
#define ID_PROJECT_OPEN_COMPILER        32792
#define ID_VIEW_FILES                   32793
#define ID_VIEW_ICONS                   32794
#define ID_VIEW_INI                     32795
#define ID_VIEW_INSTALLDELETE           32796
#define ID_VIEW_REGISTRY                32797
#define ID_VIEW_RUN                     32798
#define ID_VIEW_UNINSTALLDELETE         32799
#define ID_VIEW_UNINSTALLRUN            32800
#define ID_PROJECT_CREATE_DIRECTORY     32803
#define ID_PROJECT_INSERT_FILES         32804
#define ID_EDIT_MOVEDOWN                32817
#define ID_EDIT_MOVEUP                  32818
#define ID_VIEW_FILESASLIST             32819
#define ID_VIEW_ICONSASLIST             32820
#define ID_EDIT_DELETEITEM              32821
#define ID_VIEW_PROPERTIES              32823
#define ID_PROJECT_CREATE_ASSOCIATION   32827
#define ID_PROJECT_IMPORT_INI           32828
#define ID_FILE_PREFERENCES             32829
#define ID_PROJECT_IMPORT_REGISTRY      32830
#define ID_VIEW_MESSAGES                32834
#define ID_PROJECT_IMPORT_MESSAGES      32835
#define ID_PROJECT_COMPILE_SCRIPT       32836
#define ID_PROJECT_INSTALL_FONTS        32842
#define ID_VIEW_CUSTOMIZE               32843
#define ID_VIEW_REGISTRYASLIST          32844
#define ID__DIRECTORYCONSTANTS_DUMMY    32846
#define ID__SETUPDIRECTORIES_DUMMY      32847
#define ID__OTHERCONSTANTS_DUMMY        32848
#define ID_VIEW_SCRIPT                  32849
#define ID_EDIT_CHECK_SCRIPT            32850
#define ID_VIEW_SECTIONDROPDOWN         32851
#define ID_PROJECT_CREATE_ODBC_PROFILE  32852
#define ID_PROJECT_OPTIONS              32856
#define ID_PROJECT_OPTIONS_COMPILER     32857
#define ID_PROJECT_OPTIONS_DISKSPANNING 32858
#define ID_PROJECT_OPTIONS_APPLICATION  32859
#define ID_PROJECT_OPTIONS_USERINFO     32860
#define ID_PROJECT_OPTIONS_APPDIRECTORY 32861
#define ID_PROJECT_OPTIONS_PROGRAMGROUP 32862
#define ID_PROJECT_OPTIONS_PAGES        32863
#define ID_PROJECT_OPTIONS_APPEARANCE   32864
#define ID_PROJECT_OPTIONS_UNINSTALL    32865
#define ID_HELP_INNO_SETUP_HELP         32871
#define ID_VIEW_TYPES                   32872
#define ID_VIEW_COMPONENTS              32873
#define ID_VIEW_TASKS                   32877
#define ID_PROJECT_EXPORT_REGISTRY      32880
#define ID_VIEW_PRECOMPILATIONSTEPS     32881
#define ID_VIEW_POSTCOMPILATIONSTEPS    32882
#define ID_VIEW_DOWNLOAD                32884
#define ID_FILE_MERGE                   32885
#define ID_PROJECT_USE_ABSOLUTE_PATHS   32887
#define ID_PROJECT_RUN_SETUP            32888
#define ID_PROJECT_COMPILE_AND_RUN_SETUP 32889
#define ID_PROJECT_CREATE_BDE_ALIAS     32891
#define ID_PROJECT_CREATE_INTERNET_SHORTCUT 32893
#define ID_PROJECT_VERIFY_FILES         32894
#define ID_HELP_SEARCH                  32895
#define ID_HELP_UPDATES                 32898
#define ID_PROJECT_LANG_OPTIONS         32899
#define ID_VIEW_CODE                    32901
#define ID_PROJECT_EXPORT_MESSAGES      32902
#define ID_PROJECT_CREATE_UNINSTALL_ICON 32903
#define ID_PP_BACK                      32917
#define ID_PP_FORWARD                   32918
#define ID_PP_CLOSE                     32920
#define ID_VIEW_LANGUAGES               32924
#define ID_PROJECT_UNINSTALL            32934
#define ID_ACC_CALLTIP                  32940
#define ID_EDIT_COMMENTSELECTION        32942
#define ID_EDIT_UNCOMMENTSELECTION      32943
#define ID_HELP_ISPP                    32944
#define ID_VIEW_CUSTOMMESSAGES          32946
#define ID_HELP_INNOSETUPPREPROCESSORHELP 32947
#define IDS_ERROR_INNOFOLDER            34502
#define ID_EDIT_FIND_PREVIOUS           37126
#define ID_EDIT_INDICATOR_COL           37900
#define ID_EDIT_INDICATOR_READ          37901
#define ID_EDIT_INDICATOR_CRLF          37902
#define ID_EDIT_INDICATOR_POSITION      37903
#define WTL_IDS_APP_TITLE               0xE000
#define ID_ROW_PANE                     61204
#define ID_COL_PANE                     61205

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        272
#define _APS_NEXT_COMMAND_VALUE         32948
#define _APS_NEXT_CONTROL_VALUE         1677
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
